name: Build mod

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'

      - name: Build mod
        run: chmod 777 ./gradlew && ./gradlew build

      - uses: actions/upload-artifact@v4.6.1
        with:
          path: ./mc*/build/libs/napack-*-*.jar